spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  :datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 829247905446-imqpv821fel632m6dp4fo2ti3546njgr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


  h2:
    console:
      enabled: true

jwt:
  issuer: alswnsdl333@gmail.com
  secret_key: test_jwt_secret_key