spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: vnvnvn125a
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  issuer: alswnsdl333@gmail.com
  secret_key: test_jwt_secret_key